### ISSUE TITLE
Pop_density.csv in week 26

### ISSUE THREAD

**Issue by RickPack** [jkaupp/tidytuesdays#2]
Can you upload the pop_density.csv file that you referenced in the bivariate choropleth (UFO Sightings) code in https://github.com/jkaupp/tidytuesdays/blob/master/2019/week26/R/analysis.R?

**Comment by jkaupp** [comment]
It's already present in the week26/data directory:  https://github.com/jkaupp/tidytuesdays/blob/master/2019/week26/data/pop_density.csv
